config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put 'like', to: 'posts#upvote'
      put 'dislike', to: 'posts#downvote'
    end
    resources :comments
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { medium: "700x500#", thumb: "350x250>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @post, notice: "The comment was successfully created."
    else
      redirect_to @post, notice: "The comment failed to be created."
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params[:comment].permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @comments = @post.comments.order(created_at: :desc)
    @random_post = Post.where.not(id: @post).order("RANDOM()").first
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: "The post was created successfully."
    else
      render :new, notice: "The post failed to be created."
    end
  end

  def edit

  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, notice: "The post was successfully updated."
    else
      render :edit, notice: "The post failed to be updated."
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def upvote
    @post.upvote_by current_user
    redirect_to @post
  end

  def downvote
    @post.downvote_by current_user
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment
  %p.username= comment.user.name
  %p.content= comment.content
  

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
  = f.input :content, label: "Reply to thread"
  %br
  = f.button :submit, class: 'button'

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Forum
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %header
    .wrapper.clearfix
      #logo= link_to 'Muse', root_path
      %nav
        -if user_signed_in?
          = link_to current_user.name, edit_user_registration_path
          = link_to "Add New Inspiration", new_post_path
        - else
          = link_to 'Log in', new_user_session_path
          = link_to 'Register', new_user_registration_path
  .wrapper
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-#{name}"
  .wrapper
    = yield

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.input :image
  = f.input :title
  = f.input :link
  = f.input :description
  %br
  = f.button :submit

app/views/posts/_post.html.haml
.post
  .post_image
    %p= link_to image_tag(post.image.url(:thumb)), post
  .post_content
    .title
      %h2= link_to post.title, post
    .data.clearfix
      %p.username
        Shared by
        = post.user.name
      %p.buttons
        %span
          %i.fa.fa-comments-o
          = post.comments.count
        %span
          %i.fa.fa-thumbs-o-up
          = post.get_likes.size

app/views/posts/edit.html.haml
%h1 Edit Post
= render 'form'
= link_to 'Cancel', root_path

app/views/posts/index.html.haml
- if user_signed_in?
  %p#intro
  Hello
  = current_user.name
  %br/
  %span
    Share your inspiration and see what's inspiring others.
- else
  %p#intro
    What's your muse?
    %br/
    %span
      Share your inspiration and see what's inpiring others.
#posts
  = render @posts

app/views/posts/new.html.haml
%h1 New Post
= render 'form'
= link_to 'Cancel', root_path

app/views/posts/show.html.haml
#post_show
  %h1= @post.title
  %p.username
    Shared by
    = @post.user.name
    about
    = time_ago_in_words(@post.created_at)
  .clearfix
    .post_image_description
      = image_tag @post.image.url(:medium)
      .description= simple_format(@post.description)
    .post_data
      = link_to "Visit Link", @post.link, class: 'button'
      = link_to like_post_path(@post), method: :put, class: 'data' do
        %i.fa.fa-thumbs-o-up
        = pluralize(@post.get_upvotes.size, 'Like')
      = link_to like_post_path(@post), method: :put, class: 'data' do
        %i.fa.fa-thumbs-o-down
        = pluralize(@post.get_downvotes.size, 'Dislike')

      %p.data
        %i.fa.fa-comments-o
          = pluralize(@post.comments.count, "Comment")
      - if @post.user == current_user
        = link_to 'Edit', edit_post_path, class: 'data'
        = link_to 'Delete', post_path, method: :delete, data: { confirm: 'Are you sure?'}, class: 'data'
    #random_post
      %h3 Random Inspiration
      .post
        .post_image
          = link_to (image_tag @random_post.image.url(:thumb)), @random_post
        .post_content
          .title
            %h2= link_to @random_post.title, @random_post
          .data.clearfix
            %p.username
              Shared by
              = @random_post.user.name
            %p.buttons
              %span
                %i.fa.fa-comments-o
                = @random_post.comments.count
              %span
                %i.fa.fa-thumbs-o-up
                = @random_post.get_likes.size

#comments
  %h2.comment_count= pluralize(@post.comments.count, "Comment")
  = render @comments
  = render 'comments/form'